### ISSUE TITLE
Coupon generation takes too long causing frontend to report create campaign as failed

### ISSUE THREAD

**Issue by zognin** [Giving-Coupons/giving-coupons#174]
The creation happens successfully, but the response takes too long. Coupon generation and getting of coupon data is too long. N+1 queries.
The frontend reports it as a failed request. No user error message is even shown.

Fix: We should fix the N+1 queries and insertions. And also send a smaller response (campaign base data only) for both create and edit actions.

<img width="492" alt="Screenshot 2022-10-16 at 2 31 19 PM" src="https://user-images.githubusercontent.com/71375383/196021670-7aa9824e-1be2-44ba-8257-9075a366a69d.png">

**Comment by sivayogasubramanian** [comment]
fixed in #239
