### ISSUE TITLE
Thank you page is scrollable horizontally 

### ISSUE THREAD

**Issue by sivayogasubramanian** [Giving-Coupons/giving-coupons#290]
To also remove the thank you for donation status msg as it is not needed

**Comment by bharathcs** [comment]
I can't replicate this tho

**Comment by sivayogasubramanian** [comment]
> I can't replicate this tho

@bharathcs 

https://user-images.githubusercontent.com/53614454/197744022-bcd07005-eebd-4046-a8d7-ba3df2ade9c1.mp4
