### ISSUE TITLE
Fix campaign card style

### ISSUE THREAD

**Issue by sivayogasubramanian** [Giving-Coupons/giving-coupons#378]
<img width="427" alt="Screenshot 2022-11-02 at 2 14 20 AM" src="https://user-images.githubusercontent.com/53614454/199307660-8a452ffc-b864-4805-9a34-2a8fe8f793ec.png">

If you look closely the learn more button is protruding out of the card (zoom in and see the button bg color)

To also increase the spacing between the search and card list.

<img width="228" alt="Screenshot 2022-11-02 at 2 18 42 AM" src="https://user-images.githubusercontent.com/53614454/199308509-a6a2c4ee-8c50-4a36-b7e2-15e7597641dd.png">

**Comment by zognin** [comment]
Should fix the icons size too
